In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
# Ensures that tweet and user ids do not appear in scientific notation
pd.options.display.float_format = '{:.0f}'.format

In [17]:
german = pd.read_csv('DE-trial-text4.csv', index_col=0).dropna()
german = german.iloc[0:25000]
german['language'] = 'German'
german

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
0,636404748460130304,2752637806,INFP,@NichtLaura ðŸ˜© WÃ¼rde ich liebend gerne...glaub ...,German
1,664796614247215104,10618562,ENFP,@Gedankenmel Wenn ich wirklich sneaky sein wil...,German
3,554472793921056768,1250360954,INFP,@MissesVlog Hab zufÃ¤llig im richtigen Momment ...,German
4,630742091245690880,19249012,ENFP,@dasYuuji Ich habe die Bestellung ein zweites ...,German
5,80730947657535488,37888929,ENTP,Jetzt muss auch noch das Abendkleid am Wochene...,German
...,...,...,...,...,...
16520,463411339747409920,855190290,ENFP,ðŸ˜¨Die Mutter ist so ein Biest ðŸ˜°,German
16521,649977125165006848,63424385,INFJ,@marinaperk Zeigen!,German
16522,544534462496010240,13172082,INTP,MÃ¼sste eigentlich was wichtiges programmieren ...,German
16523,578901794908213248,1244284644,ENFP,@Doppelbeben Sieht gut aus :-).,German
16524,608368150556602368,81117087,INFJ,"Traurig das es Menschen gibt, die sich ihre La...",German

In [18]:
spanish = pd.read_csv('ES-trial-text.csv', index_col=0).dropna()
spanish = spanish.iloc[0:25000]
spanish['language'] = 'Spanish'
spanish

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
1,382700276576038912,91732481,ESTJ,El marico cualquiera cree que es la persona qu...,Spanish
2,433680598251487232,100252744,ISFJ,Una vaina es manifestar pacÃ­ficamente y otrs d...,Spanish
4,666067932791889920,458612984,ENTP,@SusanaStraus bueno todavÃ­a queda la adc de la...,Spanish
5,225207632875622400,194737197,INTJ,@kennygrullon #novoypaplaza hasta que arreglen...,Spanish
6,211997751037272064,100349273,INFP,@osojimenez tngo miedo!! Y si me marcas?,Spanish
...,...,...,...,...,...
11909,403977920214884416,190647090,INTJ,"""Sin la absoluta confianza en si mismo, uno es...",Spanish
11910,474220960732966912,50753262,INTP,NO pongo fotos de la cordillera solo pq mi dpt...,Spanish
11911,223237406411866080,90379687,ESTJ,@marianakno sip ahÃ­ la escondo en el refri,Spanish
11912,156793718328922112,40788759,ISFJ,@plomoscl cuanto sabeeeeeeeeee jajajaaj,Spanish
11914,108776795263877120,60480867,INFJ,@Beasalas feliz cumple mi bonita! Mil bendicio...,Spanish

In [19]:
italian = pd.read_csv('IT-trial-text3.csv', index_col=0).dropna()
italian = italian.iloc[0:25000]
italian['language'] = 'Italian'
italian

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
0,399583833026097216,70409384,INTP,non sono andata al lavoro per farli vincere #E...,Italian
1,693177077881794560,2973916630,INTJ,"ma se io lo volessi vedere, sto show.....",Italian
2,681396126080188416,1382370456,ENFP,ground zeroes a 5 euro. e c'Ã¨ gente che ne ha ...,Italian
3,509445790524116992,577327514,ISFP,"10. amo il kpop, se vi piace seguire la massa ...",Italian
5,669114591952117760,2222081301,INTP,"La bambina mi Ã¨ simpatica, non parla e non rom...",Italian
...,...,...,...,...,...
3594,689409004632571904,1284380995,ENTJ,beh... almeno a differenza degli altri gruppi ...,Italian
3595,649644471055949824,542772869,INTP,back from la prima lezione in palestra,Italian
3596,627011781974728704,594743639,INTJ,Scusa Twitter ma che senso ha pubblicizzarmi u...,Italian
3597,651096295264944128,1201405446,INFP,Madonna Liam ti prego ðŸ˜‚ðŸ˜‚,Italian
3599,546731988192071680,2806031165,ISTP,"""@idhuglouis: Cita e rispondi di Nonna Gualtie...",Italian

In [20]:
dutch = pd.read_csv('NL-trial-text3.csv', index_col=0).dropna()
dutch = italian.iloc[0:25000]
dutch['language'] = 'Dutch'
dutch

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
0,399583833026097216,70409384,INTP,non sono andata al lavoro per farli vincere #E...,Dutch
1,693177077881794560,2973916630,INTJ,"ma se io lo volessi vedere, sto show.....",Dutch
2,681396126080188416,1382370456,ENFP,ground zeroes a 5 euro. e c'Ã¨ gente che ne ha ...,Dutch
3,509445790524116992,577327514,ISFP,"10. amo il kpop, se vi piace seguire la massa ...",Dutch
5,669114591952117760,2222081301,INTP,"La bambina mi Ã¨ simpatica, non parla e non rom...",Dutch
...,...,...,...,...,...
3594,689409004632571904,1284380995,ENTJ,beh... almeno a differenza degli altri gruppi ...,Dutch
3595,649644471055949824,542772869,INTP,back from la prima lezione in palestra,Dutch
3596,627011781974728704,594743639,INTJ,Scusa Twitter ma che senso ha pubblicizzarmi u...,Dutch
3597,651096295264944128,1201405446,INFP,Madonna Liam ti prego ðŸ˜‚ðŸ˜‚,Dutch
3599,546731988192071680,2806031165,ISTP,"""@idhuglouis: Cita e rispondi di Nonna Gualtie...",Dutch

In [21]:
train_german, test_german = train_test_split(german, test_size=0.2, random_state=42)
train_spanish, test_spanish = train_test_split(spanish, test_size=0.2, random_state=42)
train_italian, test_italian = train_test_split(italian, test_size=0.2, random_state=42)
train_dutch, test_dutch = train_test_split(dutch, test_size=0.2, random_state=42)

In [22]:
train = pd.concat([train_german, train_spanish, train_italian, train_dutch])
train

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
14222,559463518056222720,27621196,ISFJ,@alicedeee Ich kÃ¶nnte der stundenlang zuhÃ¶ren!...,German
14668,473510634081239040,855190290,ENFP,@Moaxi @KatrinaJulie kann ich immer noch sehen...,German
889,377531414130229248,133708993,ENFJ,@GerhardMaier fand ich auch damals. Klappt das...,German
7705,578258496380149760,397366447,ENFP,38 qm fÃ¼r 700 warm ... ich muss verrÃ¼ckt sein ...,German
1585,662601975658344448,1305617798,INTP,@dilettiert Willkommen in unserer Welt. Liebe ...,German
...,...,...,...,...,...
13586,680949466871009280,542772869,INTP,accorsi la deve smettere,Dutch
8513,635612601947394048,169452362,INFP,io vado col finale\nlo faccio\nchiudo alle 4 m...,Dutch
1371,466726191257636864,98672812,ENTJ,L'evoluzione dell'Universo in una simulazione ...,Dutch
4695,561655376605872064,548470145,ESFJ,E dopo essermi addormentata fra le tue braccia...,Dutch
1551,585890144764461056,81557253,INFP,Uscire sta diventando imbarazzante: ho chiazze...,Dutch

In [23]:
test = pd.concat([test_german, test_spanish, test_italian, test_dutch])
test

,confirmed_tweet_ids,user_id,mbti,twitter_text,language
8856,158679079082659840,62117549,ENTP,Wisst ihr was das beste an #ibes ist? Dass sie...,German
15218,597014706436612096,17832573,ENFP,Ich hab Connis 7 Minuten letztes Jahr auch geh...,German
3635,134641950128214000,81568595,ENFP,"@fat_jacK47 ja, aber ich wÃ¤rs nich :D",German
1065,242712774025809920,3253641,ESTJ,@Wally44 danke. Ist runtergeladen :),German
1588,608464865997549568,3091403585,ISTP,@Patienti_A Schlaf gut,German
...,...,...,...,...,...
13638,642030068894691328,1327151641,ENTP,quel momento in cui stai pedalando tranquillam...,Dutch
18491,260711964781731840,548470145,ESFJ,uomo perfetto????? FA SCHIFOOOOOOOOOOOOOOOOOOO...,Dutch
6374,692631634366038016,201361241,INTJ,"@amerutan non ti allarmare, sto accompagnando ...",Dutch
12934,671954187303919616,164412025,INFJ,- insegnarle l'italiano e avevo tipo otto anni...,Dutch
1103,294216812768423936,8361022,ENTJ,@bisc_otti anche l'anno scorso non l'ho fatta ...,Dutch

In [24]:
train.to_csv('twisty_train.csv')

In [25]:
test.to_csv('twisty_test.csv')